# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orders.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, "", "orders.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0corders.proto"@\n\x0cOrderRequest\x12\x10\n\x08id_orden\x18\x01 \x01(\t\x12\x0f\n\x07\x63liente\x18\x02 \x01(\t\x12\r\n\x05total\x18\x03 \x01(\x02"/\n\rOrderResponse\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\x12\r\n\x05\x65xito\x18\x02 \x01(\x08\x32<\n\x0cOrderService\x12,\n\x0b\x43reateOrder\x12\r.OrderRequest\x1a\x0e.OrderResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "orders_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ORDERREQUEST"]._serialized_start = 16
    _globals["_ORDERREQUEST"]._serialized_end = 80
    _globals["_ORDERRESPONSE"]._serialized_start = 82
    _globals["_ORDERRESPONSE"]._serialized_end = 129
    _globals["_ORDERSERVICE"]._serialized_start = 131
    _globals["_ORDERSERVICE"]._serialized_end = 191
# @@protoc_insertion_point(module_scope)
